name: Do Not Merge

on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]

jobs:
  do-not-merge:
    if: ${{ contains(github.event.*.labels.*.name, 'do not merge') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Pull request is labeled as do not merge."
          echo "This workflow is set to fail so that this pull request cannot be merged."
          exit 1
